manifest:
  version: "1.2"

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.0
      clone-depth: 1
      import:
        path-prefix: .zephyr
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_espressif
          - hal_nordic
          - mbedtls
          - tinycrypt

  self:
    path: firmware
